# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='c',
            name='author',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='ajax.UserProfile'),
            preserve_default=False,
        ),
    ]
