# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 18:16
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ajax', '0004_c_liking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='c',
            name='liking',
        ),
        migrations.AddField(
            model_name='c',
            name='liking',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
