# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 20:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ajax', '0005_auto_20170626_2116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='c',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ajax.UserProfile'),
        ),
    ]
